### ISSUE TITLE
Lanzaboote Setup Not Working

### ISSUE THREAD

**Issue by bd-g** [nix-community/lanzaboote#183]
I didn't see any guidelines for how to structure this issue, so let me know what logs or information to include.

I got Lanzaboote working on another computer, so I know the process works. I copied the same process on my second machine, but secure boot doesn't work, as described in the following quick start paragraph:

```
If your system doesn't boot with Secure Boot enabled, the most likely issue is that Lanzaboote could not verify a cryptographic hash. To recover from this, disable Secure Boot in your firmware settings. Please file a bug, if you hit this issue.
```

I get the something like the following message when Secure Boot is enabled, highlighted in red

```
/boot/EFI/nixos/l8hnrsh25g105mg77d94dl1a389g07is-linux-6.3.3-bzImage.efi is not signed
```

**Comment by nikstur** [comment]
Do you get this message when you call `sbctl verify`? The kernel is not supposed to be signed because it could otherwise be used by a sort of downgrade attack where someone with access to your disks could add a systemd-boot type 1 entry and just boot your separately signed kernel.

In short: it is expected that the kernel is not signed. sbctl, however has no way of knowing that we're still booting securely.

**Comment by bd-g** [comment]
> Do you get this message when you call `sbctl verify`? The kernel is not supposed to be signed because it could otherwise be used by a sort of downgrade attack where someone with access to your disks could add a systemd-boot type 1 entry and just boot your separately signed kernel.
> 
> 
> 
> In short: it is expected that the kernel is not signed. sbctl, however has no way of knowing that we're still booting securely. 

Which is why I was surprised - it wasn't signed on my other machine either, and it was fine. But this machine, when I enable secure boot, it fails to boot with a message (not the above exactly just something like it, but specifically mentioning the bzi image) saying that piece isn't signed properly, the message highlighted in red.

**Comment by bd-g** [comment]
I found the issue. My ESP partition was corrupted, I fixed it and redid everything and it resolved it!

**Comment by nikstur** [comment]
Awesome! We actually had a similar situation recently where the ESP was corrupt and systemd-boot just showed no entries because all the kernels and initrds vanished. This would be solved if NixOS would use systemd's automounts where fsck is run on each access. Maybe we just need to add a fsck to lzbt or at least mention it in the docs.

**Comment by RaitoBezarius** [comment]
We really need to add `lzbt fsck` yes

**Comment by RaitoBezarius** [comment]
> We actually had a similar situation recently where the ESP was corrupt and systemd-boot just showed no entries because all the kernels and initrds vanished. 

I said that USB keys were not an appropriate medium for NixOS systems :DDDDDDD
FAT32 on USB keys on non-live systems := let's test how non-journaled systems fail in horrible ways :)
