### ISSUE TITLE
Hard-coded generation path in UKI module failed in non-testing environments

### ISSUE THREAD

**Issue by jnsgruk** [nix-community/lanzaboote#300]
Hey :wave: 

I was trying to get to a setup where I have secure boot with a UKI, and ran into an issue with the UKI module. I had configured like this:

```
boot = {
	bootspec.enable = true;
	systemd-boot.enable = lib.mkForce false;
	loader.uki.enable = true;
}
```

On my system this fails with the error: `jq: error: could not open file /nix/var/nix/profiles/system-1-link/boot.json` because the system is at generation 131. I think this is the [offending line](https://github.com/nix-community/lanzaboote/blob/f2bc0af580f0bb6e6a2d0bcf0cfb237b357ffbbf/nix/modules/uki.nix#L39)

(On a side note, it's not clear to me that the above config would result in a secure-booted system, given that one cannot enable `config.boot.lanzaboote` with a `pkiBundle`, because the `installHooks` collide?)

**Comment by nikstur** [comment]
The fat UKI module is really only here so that we can test the fat UKI which we want to use to eventually replace systemd-stub. It's not meant to be used with a generation based system and indeed it doesn't support Secure Boot right now.

You should use "normal" Lanzaboote instead which works way better with NixOS anyways because it still allows you to enable SecureBoot while deduplicating files on the ESP.

**Comment by RaitoBezarius** [comment]
I told @jnsgruk that theoretically speaking, this module could be used to enable true fat UKI on lanzaboote but I was not sure that it was not really exposed to front users.

**Comment by jnsgruk** [comment]
Thanks for following up. Yeh I had more of a read of the code and came to the same conclusions about what's possible right now.

There are some stability and security related benefits to using UKIs with secure boot, though clearly the duplicated kernels and initrds would consume more space on the ESP partition.

If this is a total non-goal for the project I'm happy for this to be closed out, or we could rename and track any progress toward secure boot support for UKIs.

**Comment by nikstur** [comment]
I think UKIs as they are right now are lovely but not well suited to the generation based mode of a "normal" NixOS installtion. The [original prototype for Secure Boot on NixOS](https://github.com/DeterminateSystems/bootspec-secureboot) actually started out using UKIs but then hit their limitations and that's why we started Lanzaboote.

Supporting UKIs as they are right now is a non-goal for me. 

What we are aiming for, however, is:

- Replacing the upstream systemd-stub with our fat UKI.
- Working with the systemd upstream to find a way to extend the systemd-boot Secure Boot capability so it works out of the Box for NixOS.
