### ISSUE TITLE
Better security. Initrd verification

### ISSUE THREAD

**Issue by Sk7Str1p3** [nix-community/lanzaboote#417]
The big problem of lanzaboote is its stub implementation. It makes UKIs much smaller but makes impossible to check initrd. Currently there's 3 files used for booting - executable stub, executable kernel and not executable initrd. As initrd is not executable, sbctl cannot sign it. So, to be able to verify initrd, we have 2 options:
- Merge kernel and initrd into one file and keep cmdline into stub
- Embed little linux which would call kexec and pass cmdline from stub to real kernel
This would make secure boot much more 'secure'

**Comment by RaitoBezarius** [comment]
The initrd is verified because its hash is embedded in the stub and the stub are signed. When you sign the stub, you directly sign the hash of the initrd. If you trust the code can verify adequately a cryptographic hash, then you are signing indirectly the initrd.

It seems that you want Secure Boot based signature for initrds, what does it buy you more than this model which is stricter?

**Comment by Sk7Str1p3** [comment]
Oh, i thought you left it without verification, it's just not noticed in documentation. My bad, sorry
