### ISSUE TITLE
Do a sub-0.1 release

### ISSUE THREAD

**Issue by RaitoBezarius** [nix-community/lanzaboote#66]
We should definitely do a sub-0.1 release now and then, and keep some kind of release process until 1.0 (#9).

**Comment by blitz** [comment]
What about tagging `v0.0.1` next week in time for FOSDEM? We can then do roughly monthly releases, for example. With releases, I would also like to maintain a changelog that details user-visible changes.

I'm going to create a milestone for a 1.0 and add some issues that I think we should resolve before then.

**Comment by nikstur** [comment]
I've always found it a little silly to release patch versions without a minor version.  I'd rather just start with 0.1.0.
From glancing at the semver spec, it seems to support that:

From the [FAQ](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase):

> **How should I deal with revisions in the 0.y.z initial development phase?**
> 
> The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

Otherwise I'm all in.

**Comment by blitz** [comment]
https://github.com/nix-community/lanzaboote/releases/tag/v0.1.0 :rocket:
